filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - decode_json_fields:
        fields: ["message"]
        target: ""
        overwrite_keys: true
    - add_fields:
        target: ""
        fields:
          environment: "development"
          datacenter: "local"

# Filter for our services
filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  include_lines: ['ugc-subgraph', 'apollo-router', 'users-subgraph', 'offers-subgraph']
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - decode_json_fields:
        fields: ["message"]
        target: ""
        overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644